version: "3"
services:
  waiter:
    image: monkeycodes/cafe-waiter
    container_name: waiter
    ports:
      - 6080:6080
  kitchen:
    image: monkeycodes/cafe-kitchen
    container_name: kitchen
    ports:
      - 6081:6081
  stockroom:
    image: monkeycodes/cafe-stockroom
    container_name: stockroom
    ports:
      - 6082:6082
  cashier:
    image: monkeycodes/cafe-cashier
    container_name: cashier
    ports:
      - 6083:6083
  ui:
    image: monkeycodes/cafe-ui
    container_name: ui
    ports:
      - 4200:80