axon:
  axonserver:
    enabled: false
  serializer:
    general: jackson
    events: jackson
    messages: jackson

server:
  port: 6081

spring:
  application:
    name: kitchen-service
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


management:
  endpoints:
    web:
      exposure:
        include: "health,info,beans"

kafka:
  bootstrapAddress: "127.0.0.1:9092"
  schemaRegistryAddress: "http://127.0.0.1:8081"
  producer:
    topic: "cafe.kitchen.events"
  consumer:
    group: kitchenService
