atomfeed:
  client:
    schedules:
      - cron: "*/1 * * * * *"
        url: "http://waiter:8080/feed"

kafka:
  bootstrapAddress: "host.docker.internal:9092"
  schemaRegistryAddress: "http://host.docker.internal:8081"
  producer:
    topic: "cafe.kitchen.events"
  consumer:
    group: kitchenService